// Stratum S1 — the parse-verified top stratum of Canon_Chart2.pdf.
// Rows transcribed verbatim from page 1 of the artifact, where all three numeric
// columns extract cleanly and unambiguously. Pages 2, 4, 6 and 7 of the same
// artifact extract with merged UR/GR/CR digits (e.g. "117 18", "066") and are
// therefore NOT included: transcribing a merged column is a silent measurement
// error, which is precisely the defect this project exists to prevent.

export const STRATUM = {
  id: 'S1',
  definition: 'All rows on page 1 of Canon_Chart2.pdf — the highest-CR stratum, CR 19 through 60.',
  n: 85,
  excluded:
    'Roughly 615 further rows (CR 1\u201318) remain unanalyzed. Pages 2, 4, 6 and 7 of the PDF extract with merged numeric columns and must be re-extracted from the source spreadsheet before they can be scored.',
  consequence:
    'Every statistic below describes the TOP of the chart only. It is a truncated distribution by construction \u2014 means are inflated and no chart-wide percentile can be derived from it. Treat S1 as a verified stratum, not as the frame.',
};

// t = text, a = author, f = format, s = Fiction | Nonfiction
export const S1_ROWS = [
  { t: 'Pride and Prejudice', a: 'Jane Austen', f: 'Novel', s: 'Fiction', ur: 12, gr: 48, cr: 60 },
  { t: 'The Great Gatsby', a: 'F. Scott Fitzgerald', f: 'Novella', s: 'Fiction', ur: 13, gr: 44, cr: 57 },
  { t: 'Jane Eyre', a: 'Charlotte Bronte', f: 'Novel', s: 'Fiction', ur: 14, gr: 41, cr: 55 },
  { t: 'Canterbury Tales', a: 'Geoffrey Chaucer', f: 'Poetry', s: 'Fiction', ur: 19, gr: 34, cr: 53 },
  { t: '1984', a: 'George Orwell', f: 'Novel', s: 'Fiction', ur: 10, gr: 41, cr: 51 },
  { t: 'Hamlet', a: 'William Shakespeare', f: 'Drama', s: 'Fiction', ur: 13, gr: 37, cr: 50 },
  { t: 'Wuthering Heights', a: 'Emily Bronte', f: 'Novel', s: 'Fiction', ur: 10, gr: 39, cr: 49 },
  { t: 'The Divine Comedy', a: 'Dante Alighieri', f: 'Epic', s: 'Fiction', ur: 23, gr: 25, cr: 48 },
  { t: 'Romeo and Juliet', a: 'William Shakespeare', f: 'Drama', s: 'Fiction', ur: 10, gr: 36, cr: 46 },
  { t: 'The Tempest', a: 'William Shakespeare', f: 'Drama', s: 'Fiction', ur: 18, gr: 26, cr: 44 },
  { t: 'The Odyssey', a: 'Homer', f: 'Epic', s: 'Fiction', ur: 17, gr: 26, cr: 43 },
  { t: 'The Scarlet Letter', a: 'Nathaniel Hawthorne', f: 'Novel', s: 'Fiction', ur: 9, gr: 34, cr: 43 },
  { t: 'The Adventures of Huckleberry Finn', a: 'Mark Twain', f: 'Novel', s: 'Fiction', ur: 14, gr: 28, cr: 42 },
  { t: 'Frankenstein', a: 'Mary Shelley', f: 'Novel', s: 'Fiction', ur: 10, gr: 32, cr: 42 },
  { t: 'The Catcher in the Rye', a: 'J. D. Salinger', f: 'Novel', s: 'Fiction', ur: 8, gr: 34, cr: 42 },
  { t: 'Macbeth', a: 'William Shakespeare', f: 'Drama', s: 'Fiction', ur: 14, gr: 27, cr: 41 },
  { t: 'Moby Dick, or, The Whale', a: 'Herman Melville', f: 'Novel', s: 'Fiction', ur: 12, gr: 29, cr: 41 },
  { t: 'To Kill A Mockingbird', a: 'Harper Lee', f: 'Novel', s: 'Fiction', ur: 0, gr: 41, cr: 41 },
  { t: 'Gulliver\u2019s Travels', a: 'Jonathan Swift', f: 'Novel', s: 'Fiction', ur: 13, gr: 25, cr: 38 },
  { t: 'A Midsummer Night\u2019s Dream', a: 'William Shakespeare', f: 'Drama', s: 'Fiction', ur: 12, gr: 26, cr: 38 },
  { t: 'Othello', a: 'William Shakespeare', f: 'Drama', s: 'Fiction', ur: 16, gr: 21, cr: 37 },
  { t: 'The Picture of Dorian Gray', a: 'Oscar Wilde', f: 'Novella', s: 'Fiction', ur: 8, gr: 29, cr: 37 },
  { t: 'Brave New World', a: 'Aldous Huxley', f: 'Novel', s: 'Fiction', ur: 10, gr: 26, cr: 36 },
  { t: 'King Lear', a: 'William Shakespeare', f: 'Drama', s: 'Fiction', ur: 14, gr: 21, cr: 35 },
  { t: 'Ulysses', a: 'James Joyce', f: 'Novel', s: 'Fiction', ur: 14, gr: 19, cr: 33 },
  { t: 'To The Lighthouse', a: 'Virginia Woolf', f: 'Novel', s: 'Fiction', ur: 13, gr: 20, cr: 33 },
  { t: 'Heart of Darkness', a: 'Joseph Conrad', f: 'Novel', s: 'Fiction', ur: 16, gr: 16, cr: 32 },
  { t: 'Paradise Lost', a: 'John Milton', f: 'Epic', s: 'Fiction', ur: 13, gr: 19, cr: 32 },
  { t: 'The Grapes of Wrath', a: 'John Steinbeck', f: 'Novel', s: 'Fiction', ur: 12, gr: 20, cr: 32 },
  { t: 'Crime and Punishment', a: 'Fyodor Dostoevsky', f: 'Novel', s: 'Fiction', ur: 9, gr: 23, cr: 32 },
  { t: 'Animal Farm', a: 'George Orwell', f: 'Novella', s: 'Fiction', ur: 1, gr: 31, cr: 32 },
  { t: 'The Republic', a: 'Plato', f: 'Treatise', s: 'Nonfiction', ur: 19, gr: 11, cr: 30 },
  { t: 'Walden', a: 'Henry David Thoreau', f: 'Memoir', s: 'Nonfiction', ur: 11, gr: 19, cr: 30 },
  { t: 'Dracula', a: 'Bram Stoker', f: 'Novel', s: 'Fiction', ur: 9, gr: 21, cr: 30 },
  { t: 'Oedipus Rex', a: 'Sophocles', f: 'Drama', s: 'Fiction', ur: 15, gr: 14, cr: 29 },
  { t: 'The Iliad', a: 'Homer', f: 'Epic', s: 'Fiction', ur: 14, gr: 15, cr: 29 },
  { t: 'Alice\u2019s Adventures in Wonderland', a: 'Lewis Carroll', f: 'Novel', s: 'Fiction', ur: 7, gr: 22, cr: 29 },
  { t: 'Emma', a: 'Jane Austen', f: 'Novel', s: 'Fiction', ur: 3, gr: 26, cr: 29 },
  { t: 'The Prince', a: 'Niccol\u00f2 Machiavelli', f: 'Treatise', s: 'Nonfiction', ur: 14, gr: 14, cr: 28 },
  { t: 'King James Bible', a: 'Various', f: 'Theological', s: 'Nonfiction', ur: 12, gr: 16, cr: 28 },
  { t: 'Lyrical Ballads', a: 'Wordsworth and Coleridge', f: 'Poetry', s: 'Fiction', ur: 16, gr: 11, cr: 27 },
  { t: 'Candide', a: 'Voltaire', f: 'Novella', s: 'Fiction', ur: 14, gr: 13, cr: 27 },
  { t: 'The Aeneid', a: 'Virgil', f: 'Epic', s: 'Fiction', ur: 12, gr: 15, cr: 27 },
  { t: 'Metamorphoses', a: 'Ovid', f: 'Poetry', s: 'Fiction', ur: 11, gr: 16, cr: 27 },
  { t: 'Madam Bovary', a: 'Gustave Flaubert', f: 'Novel', s: 'Fiction', ur: 9, gr: 18, cr: 27 },
  { t: 'A Tale of Two Cities', a: 'Charles Dickens', f: 'Novel', s: 'Fiction', ur: 0, gr: 27, cr: 27 },
  { t: 'The Sound and the Fury', a: 'William Faulkner', f: 'Novel', s: 'Fiction', ur: 11, gr: 15, cr: 26 },
  { t: 'Invisible Man', a: 'Ralph Ellison', f: 'Novel', s: 'Fiction', ur: 11, gr: 15, cr: 26 },
  { t: 'Dr. Jekyll and Mr. Hyde', a: 'Robert Louis Stevenson', f: 'Novella', s: 'Fiction', ur: 10, gr: 16, cr: 26 },
  { t: 'Leaves of Grass', a: 'Walt Whitman', f: 'Poetry', s: 'Fiction', ur: 9, gr: 17, cr: 26 },
  { t: 'Don Quixote', a: 'Miguel de Cervantes', f: 'Novel', s: 'Fiction', ur: 6, gr: 20, cr: 26 },
  { t: 'The Merchant of Venice', a: 'William Shakespeare', f: 'Drama', s: 'Fiction', ur: 10, gr: 15, cr: 25 },
  { t: 'Of Mice and Men', a: 'John Steinbeck', f: 'Novel', s: 'Fiction', ur: 2, gr: 23, cr: 25 },
  { t: 'One Hundred Years of Solitude', a: 'Gabriel Garcia Marquez', f: 'Novel', s: 'Fiction', ur: 2, gr: 23, cr: 25 },
  { t: 'Anna Karenina', a: 'Leo Tolstoy', f: 'Novel', s: 'Fiction', ur: 1, gr: 24, cr: 25 },
  { t: 'Confessions', a: 'Augustine of Hippo', f: 'Autobiography', s: 'Nonfiction', ur: 15, gr: 9, cr: 24 },
  { t: 'The Communist Manifesto', a: 'Marx and Engels', f: 'Political', s: 'Nonfiction', ur: 14, gr: 10, cr: 24 },
  { t: 'Mrs. Dalloway', a: 'Virginia Woolf', f: 'Novel', s: 'Fiction', ur: 14, gr: 10, cr: 24 },
  { t: 'Twelfth Night', a: 'William Shakespeare', f: 'Drama', s: 'Fiction', ur: 9, gr: 15, cr: 24 },
  { t: 'Waiting for Godot', a: 'Samuel Beckett', f: 'Drama', s: 'Fiction', ur: 9, gr: 15, cr: 24 },
  { t: 'War and Peace', a: 'Leo Tolstoy', f: 'Novel', s: 'Fiction', ur: 3, gr: 21, cr: 24 },
  { t: 'Sonnets', a: 'William Shakespeare', f: 'Poetry', s: 'Fiction', ur: 12, gr: 11, cr: 23 },
  { t: 'Beloved', a: 'Toni Morrison', f: 'Novel', s: 'Fiction', ur: 9, gr: 14, cr: 23 },
  { t: 'The Sun Also Rises', a: 'Ernest Hemingway', f: 'Novel', s: 'Fiction', ur: 8, gr: 15, cr: 23 },
  { t: 'Sense and Sensibility', a: 'Jane Austen', f: 'Novel', s: 'Fiction', ur: 0, gr: 23, cr: 23 },
  { t: 'Robinson Crusoe', a: 'Daniel Defoe', f: 'Novel', s: 'Fiction', ur: 0, gr: 23, cr: 23 },
  { t: 'Their Eyes Were Watching God', a: 'Zora Neale Hurston', f: 'Novel', s: 'Fiction', ur: 9, gr: 13, cr: 22 },
  { t: 'A Portrait of the Artist as a Young Man', a: 'James Joyce', f: 'Novel', s: 'Fiction', ur: 9, gr: 13, cr: 22 },
  { t: 'The Brothers Karamazov', a: 'Fyodor Dostoevsky', f: 'Novel', s: 'Fiction', ur: 3, gr: 19, cr: 22 },
  { t: 'Lolita', a: 'Vladimir Nabokov', f: 'Novel', s: 'Fiction', ur: 2, gr: 20, cr: 22 },
  { t: 'Middlemarch', a: 'George Eliot', f: 'Novel', s: 'Fiction', ur: 2, gr: 20, cr: 22 },
  { t: 'On the Origin of Species', a: 'Charles Darwin', f: 'Treatise', s: 'Nonfiction', ur: 12, gr: 9, cr: 21 },
  { t: 'Death of a Salesman', a: 'Arthur Miller', f: 'Drama', s: 'Fiction', ur: 11, gr: 10, cr: 21 },
  { t: 'The Waste Land', a: 'T. S. Eliot', f: 'Poetry', s: 'Fiction', ur: 10, gr: 11, cr: 21 },
  { t: 'Slaughterhouse Five', a: 'Kurt Vonnegut', f: 'Novel', s: 'Fiction', ur: 6, gr: 15, cr: 21 },
  { t: 'Northanger Abbey', a: 'Jane Austen', f: 'Novel', s: 'Fiction', ur: 6, gr: 15, cr: 21 },
  { t: 'A Doll\u2019s House', a: 'Henrik Ibsen', f: 'Drama', s: 'Fiction', ur: 12, gr: 8, cr: 20 },
  { t: 'Tess of the D\u2019urbervilles', a: 'Thomas Hardy', f: 'Novel', s: 'Fiction', ur: 6, gr: 14, cr: 20 },
  { t: 'Julius Caesar', a: 'William Shakespeare', f: 'Drama', s: 'Fiction', ur: 3, gr: 17, cr: 20 },
  { t: 'Beowulf', a: 'Anonymous', f: 'Epic', s: 'Fiction', ur: 3, gr: 17, cr: 20 },
  { t: 'Antigone', a: 'Sophocles', f: 'Drama', s: 'Fiction', ur: 14, gr: 5, cr: 19 },
  { t: 'The Decameron', a: 'Giovanni Boccaccio', f: 'Anthology', s: 'Fiction', ur: 8, gr: 11, cr: 19 },
  { t: 'The Tell-Tale Heart', a: 'Edgar Allan Poe', f: 'Novella', s: 'Fiction', ur: 6, gr: 13, cr: 19 },
  { t: 'The Taming of the Shrew', a: 'William Shakespeare', f: 'Drama', s: 'Fiction', ur: 2, gr: 17, cr: 19 },
  { t: 'The Adventures of Tom Sawyer', a: 'Mark Twain', f: 'Novel', s: 'Fiction', ur: 0, gr: 19, cr: 19 },
];