/**
 * PromptMaster — 45-Chapter Data
 * SGT Ramos: The Mathematics of Vietnam
 * Baseline Ω: 105.18 | Target: 113+
 */

export const BASELINE = 105.18;
export const PROJ_MEAN = 106.54;
export const TARGET_OMEGA = 113.0;
export const ELITE_THRESHOLD = 109.5;

export const CHAPTER_DATA = [
  { n: 1,  title: 'La Promesa',                  act: 'I',   omega: 106.2, cls: 88, bis: 90, sii: 82, mrf: 85, words: 3240, dialogue_pct: 28, cs_pct: 4.1, status: 'scored',  priority: 'immediate', tier: 'strong',    sprint: 'SPRINT_1', notes: 'Jasmine-napalm anchor — 3 sensory inserts needed. PBI says +1.8Ω possible.' },
  { n: 2,  title: 'El Barrio',                   act: 'I',   omega: 104.8, cls: 82, bis: 85, sii: 78, mrf: 80, words: 2980, dialogue_pct: 31, cs_pct: 5.2, status: 'scored',  priority: 'next',      tier: 'mid',       sprint: 'SPRINT_1', notes: 'Barrio texture weakest in Act I. East LA specificity needed.' },
  { n: 3,  title: 'La Recluta',                  act: 'I',   omega: 105.1, cls: 84, bis: 87, sii: 80, mrf: 82, words: 3100, dialogue_pct: 35, cs_pct: 3.8, status: 'scored',  priority: 'routine',   tier: 'strong',    sprint: 'SPRINT_1', notes: 'Draft board scene. DCAS erasure consciousness needs reinforcement.' },
  { n: 4,  title: 'Fort Ord',                    act: 'I',   omega: 104.2, cls: 80, bis: 83, sii: 76, mrf: 79, words: 2850, dialogue_pct: 38, cs_pct: 6.1, status: 'scored',  priority: 'next',      tier: 'mid',       sprint: 'SPRINT_2', notes: 'Military terminology check needed. Radio procedure verification.' },
  { n: 5,  title: 'La Serpiente',                act: 'I',   omega: 106.8, cls: 90, bis: 88, sii: 84, mrf: 86, words: 3350, dialogue_pct: 25, cs_pct: 3.2, status: 'scored',  priority: 'routine',   tier: 'strong',    sprint: 'SPRINT_2', notes: 'Strong CLS. Battle Mysticism framework emerging.' },
  { n: 6,  title: 'Los Hermanos',                act: 'I',   omega: 105.5, cls: 85, bis: 86, sii: 81, mrf: 83, words: 3050, dialogue_pct: 42, cs_pct: 7.3, status: 'scored',  priority: 'next',      tier: 'strong',    sprint: 'SPRINT_2', notes: 'Carnalismo voice — familia logic check. Generic solidarity flagged.' },
  { n: 7,  title: 'El Cruce',                    act: 'I',   omega: 103.9, cls: 78, bis: 82, sii: 74, mrf: 77, words: 2720, dialogue_pct: 29, cs_pct: 4.5, status: 'scored',  priority: 'next',      tier: 'mid',       sprint: 'SPRINT_3', notes: 'Border crossing sequence. Geographic accuracy review needed.' },
  { n: 8,  title: 'La Víspera',                  act: 'I',   omega: 107.1, cls: 91, bis: 89, sii: 85, mrf: 87, words: 3420, dialogue_pct: 22, cs_pct: 2.9, status: 'scored',  priority: 'routine',   tier: 'strong',    sprint: 'SPRINT_3', notes: 'Pre-deployment. Familia scene strongest in Act I.' },
  { n: 9,  title: 'First Blood',                 act: 'I',   omega: 101.5, cls: 72, bis: 75, sii: 68, mrf: 71, words: 2580, dialogue_pct: 18, cs_pct: 2.1, status: 'blocker', priority: 'immediate', tier: 'weak',      sprint: 'SPRINT_3', notes: 'BLOCKER: Composite 1.52 — lowest in manuscript. BIS rewrite required. P0.' },
  { n: 10, title: 'El Infierno',                 act: 'I',   omega: 105.8, cls: 86, bis: 88, sii: 82, mrf: 84, words: 3180, dialogue_pct: 26, cs_pct: 4.8, status: 'scored',  priority: 'routine',   tier: 'strong',    sprint: 'SPRINT_3', notes: 'Combat entry. Sensory constants tracker: copper + cordite present.' },
  { n: 11, title: 'La Niebla',                   act: 'II',  omega: 106.4, cls: 87, bis: 89, sii: 83, mrf: 85, words: 3290, dialogue_pct: 30, cs_pct: 5.0, status: 'scored',  priority: 'routine',   tier: 'strong',    sprint: 'SPRINT_4', notes: 'Fog of war sequence. 60Hz sensory motif needs insertion.' },
  { n: 12, title: 'El Fantasma',                 act: 'II',  omega: 104.5, cls: 81, bis: 84, sii: 79, mrf: 81, words: 2910, dialogue_pct: 27, cs_pct: 3.7, status: 'scored',  priority: 'next',      tier: 'mid',       sprint: 'SPRINT_4', notes: 'OVERLAP: Active blocker + word count blocker. 2 blockers.' },
  { n: 13, title: 'Los Muertos',                 act: 'II',  omega: 107.8, cls: 92, bis: 91, sii: 87, mrf: 88, words: 3510, dialogue_pct: 20, cs_pct: 2.6, status: 'scored',  priority: 'routine',   tier: 'strong',    sprint: 'SPRINT_4', notes: 'Battle Mysticism peak. Dia de los Muertos frequency — strong.' },
  { n: 14, title: 'El Médico',                   act: 'II',  omega: 105.2, cls: 83, bis: 86, sii: 80, mrf: 82, words: 3020, dialogue_pct: 45, cs_pct: 8.2, status: 'scored',  priority: 'next',      tier: 'strong',    sprint: 'SPRINT_5', notes: 'Medic terminology check. High CS% — verify function tags.' },
  { n: 15, title: 'La Emboscada',                act: 'II',  omega: 108.2, cls: 93, bis: 90, sii: 88, mrf: 89, words: 3580, dialogue_pct: 19, cs_pct: 2.3, status: 'scored',  priority: 'routine',   tier: 'near-elite',sprint: 'SPRINT_5', notes: 'Near-Elite. Ambush sequence — cinematic potential high.' },
  { n: 16, title: 'El Silencio',                 act: 'II',  omega: 106.1, cls: 86, bis: 88, sii: 83, mrf: 85, words: 3230, dialogue_pct: 15, cs_pct: 1.8, status: 'scored',  priority: 'routine',   tier: 'strong',    sprint: 'SPRINT_5', notes: 'After-action sequence. Low dialogue intentional — verify.' },
  { n: 17, title: 'DUP-001 — La Duplicación',   act: 'II',  omega: 104.1, cls: 80, bis: 83, sii: 77, mrf: 80, words: 4729, dialogue_pct: 33, cs_pct: 4.4, status: 'blocker', priority: 'immediate', tier: 'mid',       sprint: 'SPRINT_5', notes: 'BLOCKER P0.DUP-001: 4,729-word overlap with Ch.18. Resolve before CLS pass.' },
  { n: 18, title: 'DUP-002 — El Eco',           act: 'II',  omega: 103.8, cls: 79, bis: 82, sii: 76, mrf: 79, words: 4729, dialogue_pct: 32, cs_pct: 4.2, status: 'blocker', priority: 'immediate', tier: 'mid',       sprint: 'SPRINT_5', notes: 'BLOCKER P0.DUP-002: Duplicate of Ch.17. Resolution: split or merge.' },
  { n: 19, title: 'El Río',                      act: 'II',  omega: 106.7, cls: 88, bis: 90, sii: 84, mrf: 86, words: 3370, dialogue_pct: 28, cs_pct: 4.9, status: 'scored',  priority: 'routine',   tier: 'strong',    sprint: 'SPRINT_6', notes: 'River crossing. Yerba buena sensory motif — present.' },
  { n: 20, title: 'La Verdad',                   act: 'II',  omega: 105.9, cls: 85, bis: 87, sii: 82, mrf: 84, words: 3140, dialogue_pct: 36, cs_pct: 5.7, status: 'scored',  priority: 'next',      tier: 'strong',    sprint: 'SPRINT_6', notes: 'Truth / moral weight scene. High emotional resonance potential.' },
  { n: 21, title: 'El Puente',                   act: 'II',  omega: 107.4, cls: 91, bis: 90, sii: 86, mrf: 87, words: 3460, dialogue_pct: 24, cs_pct: 3.1, status: 'scored',  priority: 'routine',   tier: 'strong',    sprint: 'SPRINT_6', notes: 'Bridge scene — structural metaphor. Battle Mysticism ancestral frequency.' },
  { n: 22, title: 'Los 349',                     act: 'II',  omega: 109.1, cls: 95, bis: 94, sii: 90, mrf: 91, words: 3640, dialogue_pct: 22, cs_pct: 2.8, status: 'scored',  priority: 'immediate', tier: 'near-elite',sprint: 'SPRINT_6', notes: 'The 349 Anomaly chapter — strongest external-facing asset. Push to Elite.' },
  { n: 23, title: 'La Carta',                    act: 'II',  omega: 105.4, cls: 84, bis: 86, sii: 81, mrf: 83, words: 3070, dialogue_pct: 40, cs_pct: 6.8, status: 'scored',  priority: 'next',      tier: 'strong',    sprint: 'SPRINT_7', notes: 'Letter home scene. Familia voice check.' },
  { n: 24, title: 'El Punto de Quiebre',         act: 'II',  omega: 108.5, cls: 93, bis: 91, sii: 89, mrf: 90, words: 3590, dialogue_pct: 21, cs_pct: 2.5, status: 'scored',  priority: 'next',      tier: 'near-elite',sprint: 'SPRINT_7', notes: 'Breaking point. Near-Elite. Moral weight scene — high BIS.' },
  { n: 25, title: 'La Noche',                    act: 'II',  omega: 106.3, cls: 87, bis: 89, sii: 83, mrf: 85, words: 3260, dialogue_pct: 17, cs_pct: 1.5, status: 'scored',  priority: 'routine',   tier: 'strong',    sprint: 'SPRINT_7', notes: 'Night patrol. Sensory density strong. 60Hz + cordite confirmed.' },
  { n: 26, title: 'El Prisionero',               act: 'II',  omega: 104.7, cls: 82, bis: 85, sii: 79, mrf: 81, words: 2940, dialogue_pct: 48, cs_pct: 9.1, status: 'scored',  priority: 'next',      tier: 'mid',       sprint: 'SPRINT_7', notes: 'POW interrogation scene. Highest CS% in manuscript — verify all function tags.' },
  { n: 27, title: 'La Misión',                   act: 'II',  omega: 107.0, cls: 90, bis: 89, sii: 85, mrf: 87, words: 3410, dialogue_pct: 26, cs_pct: 3.5, status: 'scored',  priority: 'routine',   tier: 'strong',    sprint: 'SPRINT_8', notes: 'Special ops mission. SOG protocol verification needed.' },
  { n: 28, title: 'El Hermano Caído',            act: 'II',  omega: 108.8, cls: 94, bis: 92, sii: 90, mrf: 91, words: 3620, dialogue_pct: 20, cs_pct: 2.4, status: 'scored',  priority: 'next',      tier: 'near-elite',sprint: 'SPRINT_8', notes: 'KIA scene. Carnalismo at highest register. Near-Elite push viable.' },
  { n: 29, title: 'La Vigilia',                  act: 'II',  omega: 107.6, cls: 91, bis: 90, sii: 87, mrf: 88, words: 3490, dialogue_pct: 18, cs_pct: 2.0, status: 'scored',  priority: 'routine',   tier: 'strong',    sprint: 'SPRINT_8', notes: 'Vigil scene. Battle Mysticism — La Llorona frequency. Strong.' },
  { n: 30, title: 'El Regreso',                  act: 'II',  omega: 105.6, cls: 85, bis: 87, sii: 82, mrf: 84, words: 3090, dialogue_pct: 31, cs_pct: 5.1, status: 'scored',  priority: 'routine',   tier: 'strong',    sprint: 'SPRINT_8', notes: 'Return patrol. Dresser cold sensory motif — needs insertion.' },
  { n: 31, title: 'La Frontera Interior',        act: 'III', omega: 106.9, cls: 89, bis: 90, sii: 85, mrf: 86, words: 3390, dialogue_pct: 29, cs_pct: 4.6, status: 'scored',  priority: 'routine',   tier: 'strong',    sprint: 'SPRINT_9', notes: 'Interior border — Chicano identity pressure. CLS strong.' },
  { n: 32, title: 'El Juicio',                   act: 'III', omega: 107.3, cls: 91, bis: 90, sii: 86, mrf: 87, words: 3450, dialogue_pct: 44, cs_pct: 7.9, status: 'scored',  priority: 'next',      tier: 'strong',    sprint: 'SPRINT_9', notes: 'Court martial scene. High dialogue. Military legal procedure check.' },
  { n: 33, title: 'La Memoria',                  act: 'III', omega: 108.1, cls: 92, bis: 91, sii: 88, mrf: 89, words: 3560, dialogue_pct: 23, cs_pct: 3.0, status: 'scored',  priority: 'routine',   tier: 'near-elite',sprint: 'SPRINT_9', notes: 'Body memory scene. Near-Elite. Grief index strong.' },
  { n: 34, title: 'Los Fantasmas del Barrio',    act: 'III', omega: 106.6, cls: 88, bis: 89, sii: 84, mrf: 86, words: 3320, dialogue_pct: 35, cs_pct: 6.2, status: 'scored',  priority: 'next',      tier: 'strong',    sprint: 'SPRINT_9', notes: 'Barrio return. Family voice — strongest in Act III.' },
  { n: 35, title: 'La Cicatriz',                 act: 'III', omega: 107.7, cls: 91, bis: 90, sii: 87, mrf: 88, words: 3500, dialogue_pct: 26, cs_pct: 3.3, status: 'scored',  priority: 'routine',   tier: 'strong',    sprint: 'SPRINT_10', notes: 'Scar scene. Folder warmth sensory motif — present.' },
  { n: 36, title: 'El Testigo',                  act: 'III', omega: 109.4, cls: 95, bis: 94, sii: 91, mrf: 92, words: 3660, dialogue_pct: 21, cs_pct: 2.7, status: 'scored',  priority: 'immediate', tier: 'near-elite',sprint: 'SPRINT_10', notes: 'Witness scene. Near-Elite at 109.4 — 0.1 from Elite. Single SII insert.' },
  { n: 37, title: 'La Justicia',                 act: 'III', omega: 107.9, cls: 92, bis: 91, sii: 88, mrf: 89, words: 3530, dialogue_pct: 38, cs_pct: 6.5, status: 'scored',  priority: 'next',      tier: 'strong',    sprint: 'SPRINT_10', notes: 'Justice scene. High dialogue + CS — function tag audit needed.' },
  { n: 38, title: 'El Sacrificio',               act: 'III', omega: 110.1, cls: 96, bis: 95, sii: 92, mrf: 93, words: 3710, dialogue_pct: 19, cs_pct: 2.2, status: 'scored',  priority: 'routine',   tier: 'elite',     sprint: 'SPRINT_10', notes: 'ELITE. Sacrifice — Battle Mysticism at full power. Lock this chapter.' },
  { n: 39, title: 'El Nombre',                   act: 'III', omega: 108.9, cls: 94, bis: 92, sii: 90, mrf: 91, words: 3630, dialogue_pct: 22, cs_pct: 2.9, status: 'scored',  priority: 'immediate', tier: 'near-elite',sprint: 'SPRINT_10', notes: 'The name scene. SII insert (jasmine-napalm anchor 200 words) → +1.8Ω → 110.7.' },
  { n: 40, title: 'La Herencia',                 act: 'III', omega: 107.5, cls: 91, bis: 90, sii: 87, mrf: 88, words: 3480, dialogue_pct: 27, cs_pct: 3.6, status: 'scored',  priority: 'routine',   tier: 'strong',    sprint: 'SPRINT_11', notes: 'Heritage scene. Barrio texture + historia present.' },
  { n: 41, title: 'El Regreso a la Tierra',      act: 'III', omega: 106.8, cls: 88, bis: 89, sii: 85, mrf: 86, words: 3370, dialogue_pct: 30, cs_pct: 4.7, status: 'scored',  priority: 'routine',   tier: 'strong',    sprint: 'SPRINT_11', notes: 'Return to earth. Sensory constants — all 6 present.' },
  { n: 42, title: 'La Ofrenda',                  act: 'III', omega: 111.2, cls: 97, bis: 96, sii: 93, mrf: 94, words: 3780, dialogue_pct: 18, cs_pct: 2.0, status: 'scored',  priority: 'routine',   tier: 'elite',     sprint: 'SPRINT_11', notes: 'ELITE. Ofrenda — highest CLS in manuscript. Protect at all costs.' },
  { n: 43, title: 'Los Soldados Olvidados',      act: 'III', omega: 108.4, cls: 93, bis: 91, sii: 89, mrf: 90, words: 3600, dialogue_pct: 25, cs_pct: 3.2, status: 'scored',  priority: 'next',      tier: 'near-elite',sprint: 'SPRINT_11', notes: 'The forgotten soldiers — 349 Anomaly callback. Near-Elite. DCAS data.' },
  { n: 44, title: 'El Matemático',               act: 'III', omega: 109.8, cls: 95, bis: 94, sii: 91, mrf: 92, words: 3680, dialogue_pct: 20, cs_pct: 2.5, status: 'scored',  priority: 'immediate', tier: 'elite',     sprint: 'SPRINT_11', notes: 'ELITE. The mathematician — title chapter. Formula must be locked here.' },
  { n: 45, title: 'La Última Batalla',           act: 'III', omega: 112.0, cls: 98, bis: 97, sii: 94, mrf: 95, words: 3850, dialogue_pct: 17, cs_pct: 1.8, status: 'scored',  priority: 'immediate', tier: 'elite',     sprint: 'SPRINT_11', notes: 'ELITE. Final chapter — highest Ω in manuscript at 112.0. The ceiling push.' },
];

export const SPRINTS = {
  SPRINT_1: { chapters: [1, 2, 3], label: 'Sprint 1' },
  SPRINT_2: { chapters: [4, 5, 6], label: 'Sprint 2' },
  SPRINT_3: { chapters: [7, 8, 9, 10], label: 'Sprint 3' },
  SPRINT_4: { chapters: [11, 12, 13], label: 'Sprint 4' },
  SPRINT_5: { chapters: [14, 15, 16, 17, 18], label: 'Sprint 5' },
  SPRINT_6: { chapters: [19, 20, 21, 22], label: 'Sprint 6' },
  SPRINT_7: { chapters: [23, 24, 25, 26], label: 'Sprint 7' },
  SPRINT_8: { chapters: [27, 28, 29, 30], label: 'Sprint 8' },
  SPRINT_9: { chapters: [31, 32, 33, 34], label: 'Sprint 9' },
  SPRINT_10: { chapters: [35, 36, 37, 38, 39], label: 'Sprint 10' },
  SPRINT_11: { chapters: [40, 41, 42, 43, 44, 45], label: 'Sprint 11' },
};

export const AUDIT_V3_DATE = '2026-06-30';
export const AUDIT_V3_CRITICAL_FINDING = 'Mean composite authenticity 2.27/5.0 — Barrio Texture 1.5, Historical Truth 1.9, Familia 1.9. DUP-001/002 (Ch.17/18) unresolved.';